/*
 * generated by Xtext 2.32.0
 */
package org.xtext.iec62443.baseModel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MiecUiModule extends AbstractMiecUiModule {

	public MiecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
