/*
 * generated by Xtext 2.32.0
 */
package org.xtext.iec62443.baseModel.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.iec62443.baseModel.ui.internal.BaseModelActivator;

public class MiecUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BaseModelActivator.getInstance().getInjector("org.xtext.iec62443.baseModel.Miec");
	}

}
