/*
 * generated by Xtext 2.32.0
 */
package org.xtext.iec62443.baseModel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMiecScopeProvider extends DelegatingScopeProvider {
}
