/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.Component#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.Component#getCapability <em>Capability</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.Component#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getComponent()
 * @model abstract="true"
 * @generated
 */
public interface Component extends EObject {
	
	// Defines constants for component type
	public static final int APPLICATION = 0;
	public static final int DEVICE = 1;
	public static final int SYSTEM = 2;
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getComponent_Name()
	 * @model required="true"
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.Component#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Capability</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Capability</em>' containment reference.
	 * @see #setCapability(SecurityLevels)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getComponent_Capability()
	 * @model containment="true" required="true"
	 * @generated
	 */
	SecurityLevels getCapability();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.Component#getCapability <em>Capability</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Capability</em>' containment reference.
	 * @see #getCapability()
	 * @generated
	 */
	void setCapability(SecurityLevels value);

	/**
	 * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.iec62443.baseModel.mIEC.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Properties</em>' containment reference list.
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getComponent_Properties()
	 * @model containment="true"
	 * @generated
	 */
	EList<Property> getProperties();

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @model kind="operation" required="true"
	 * @generated
	 */
	int getType();
	
	
	// Get the zone containing the component
	public Zone getZone();
	
	// Returns the property with the name, or null if it does not exist
	Property getProperty(String name);

} // Component
