/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Counter Measure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#getCapability <em>Capability</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#getCost <em>Cost</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#isInactive <em>Inactive</em>}</li>
 * </ul>
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getCounterMeasure()
 * @model
 * @generated
 */
public interface CounterMeasure extends EObject {
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getCounterMeasure_Name()
	 * @model required="true"
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Capability</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Capability</em>' containment reference.
	 * @see #setCapability(SecurityLevels)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getCounterMeasure_Capability()
	 * @model containment="true" required="true"
	 * @generated
	 */
	SecurityLevels getCapability();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#getCapability <em>Capability</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Capability</em>' containment reference.
	 * @see #getCapability()
	 * @generated
	 */
	void setCapability(SecurityLevels value);

	/**
	 * Returns the value of the '<em><b>Cost</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Cost</em>' containment reference.
	 * @see #setCost(IntegerValue)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getCounterMeasure_Cost()
	 * @model containment="true"
	 * @generated
	 */
	IntegerValue getCost();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#getCost <em>Cost</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Cost</em>' containment reference.
	 * @see #getCost()
	 * @generated
	 */
	void setCost(IntegerValue value);

	/**
	 * Returns the value of the '<em><b>Inactive</b></em>' attribute.
	 * The default value is <code>"false"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Inactive</em>' attribute.
	 * @see #setInactive(boolean)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getCounterMeasure_Inactive()
	 * @model default="false" required="true"
	 * @generated
	 */
	boolean isInactive();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.CounterMeasure#isInactive <em>Inactive</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Inactive</em>' attribute.
	 * @see #isInactive()
	 * @generated
	 */
	void setInactive(boolean value);

} // CounterMeasure
