/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getDeviceReference()
 * @model
 * @generated
 */
public interface DeviceReference extends Reference {
} // DeviceReference
