/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;

import org.xtext.iec62443.baseModel.mIEC.impl.ApplicationImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getNumberExpression()
 * @model abstract="true"
 * @generated
 */
public interface NumberExpression extends Expression {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @model kind="operation" required="true"
	 * @generated
	 */
	int getType();

	
	public static class ComputationErrorException extends Exception { 
	    public ComputationErrorException(String errorMessage) {
	        super(errorMessage);
	    }
	}
	
	// Returns an integer value corresponding to the computed expression
	float computeValue(Application application, Device device) throws ComputationErrorException;
	
	
} // NumberExpression
