/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.OperationNumber#getOperation <em>Operation</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.OperationNumber#getOp1 <em>Op1</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.OperationNumber#getOp2 <em>Op2</em>}</li>
 * </ul>
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getOperationNumber()
 * @model
 * @generated
 */
public interface OperationNumber extends NumberExpression {
	/**
	 * Returns the value of the '<em><b>Operation</b></em>' attribute.
	 * The default value is <code>"max"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.NumberOperationFunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Operation</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.NumberOperationFunction
	 * @see #setOperation(NumberOperationFunction)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getOperationNumber_Operation()
	 * @model default="max" required="true"
	 * @generated
	 */
	NumberOperationFunction getOperation();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.OperationNumber#getOperation <em>Operation</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Operation</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.NumberOperationFunction
	 * @see #getOperation()
	 * @generated
	 */
	void setOperation(NumberOperationFunction value);

	/**
	 * Returns the value of the '<em><b>Op1</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Op1</em>' containment reference.
	 * @see #setOp1(NumberExpression)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getOperationNumber_Op1()
	 * @model containment="true" required="true"
	 * @generated
	 */
	NumberExpression getOp1();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.OperationNumber#getOp1 <em>Op1</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Op1</em>' containment reference.
	 * @see #getOp1()
	 * @generated
	 */
	void setOp1(NumberExpression value);

	/**
	 * Returns the value of the '<em><b>Op2</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Op2</em>' containment reference.
	 * @see #setOp2(NumberExpression)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getOperationNumber_Op2()
	 * @model containment="true" required="true"
	 * @generated
	 */
	NumberExpression getOp2();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.OperationNumber#getOp2 <em>Op2</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Op2</em>' containment reference.
	 * @see #getOp2()
	 * @generated
	 */
	void setOp2(NumberExpression value);

} // OperationNumber
