/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.OperationConstraint#getOperation <em>Operation</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.OperationConstraint#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getOperationConstraint()
 * @model
 * @generated
 */
public interface OperationConstraint extends Constraint {
	/**
	 * Returns the value of the '<em><b>Operation</b></em>' attribute.
	 * The default value is <code>"eq"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Operation</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.Operation
	 * @see #setOperation(Operation)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getOperationConstraint_Operation()
	 * @model default="eq" required="true"
	 * @generated
	 */
	Operation getOperation();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.OperationConstraint#getOperation <em>Operation</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Operation</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.Operation
	 * @see #getOperation()
	 * @generated
	 */
	void setOperation(Operation value);

	/**
	 * Returns the value of the '<em><b>Value</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Value</em>' containment reference.
	 * @see #setValue(ValueOrReference)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getOperationConstraint_Value()
	 * @model containment="true" required="true"
	 * @generated
	 */
	ValueOrReference getValue();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.OperationConstraint#getValue <em>Value</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Value</em>' containment reference.
	 * @see #getValue()
	 * @generated
	 */
	void setValue(ValueOrReference value);

} // OperationConstraint
