/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getReferenceExpression()
 * @model abstract="true"
 * @generated
 */
public interface ReferenceExpression extends BooleanExpression, NumberExpression, StringExpression {
} // ReferenceExpression
