/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Security Levels</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getAccessControl <em>Access Control</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getUseControl <em>Use Control</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getSystemIntegrity <em>System Integrity</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getDataConfidentiality <em>Data Confidentiality</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getRestrictedDataFlow <em>Restricted Data Flow</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getTimelyResponse <em>Timely Response</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getResourceAvailability <em>Resource Availability</em>}</li>
 * </ul>
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels()
 * @model
 * @generated
 */
public interface SecurityLevels extends EObject {
	/**
	 * Returns the value of the '<em><b>Access Control</b></em>' attribute.
	 * The default value is <code>"SL4"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.SecurityLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Access Control</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #setAccessControl(SecurityLevel)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels_AccessControl()
	 * @model default="SL4" unique="false" required="true"
	 * @generated
	 */
	SecurityLevel getAccessControl();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getAccessControl <em>Access Control</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Access Control</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #getAccessControl()
	 * @generated
	 */
	void setAccessControl(SecurityLevel value);

	/**
	 * Returns the value of the '<em><b>Use Control</b></em>' attribute.
	 * The default value is <code>"SL4"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.SecurityLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Use Control</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #setUseControl(SecurityLevel)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels_UseControl()
	 * @model default="SL4" unique="false" required="true"
	 * @generated
	 */
	SecurityLevel getUseControl();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getUseControl <em>Use Control</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Use Control</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #getUseControl()
	 * @generated
	 */
	void setUseControl(SecurityLevel value);

	/**
	 * Returns the value of the '<em><b>System Integrity</b></em>' attribute.
	 * The default value is <code>"SL4"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.SecurityLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>System Integrity</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #setSystemIntegrity(SecurityLevel)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels_SystemIntegrity()
	 * @model default="SL4" unique="false" required="true"
	 * @generated
	 */
	SecurityLevel getSystemIntegrity();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getSystemIntegrity <em>System Integrity</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>System Integrity</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #getSystemIntegrity()
	 * @generated
	 */
	void setSystemIntegrity(SecurityLevel value);

	/**
	 * Returns the value of the '<em><b>Data Confidentiality</b></em>' attribute.
	 * The default value is <code>"SL4"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.SecurityLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Data Confidentiality</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #setDataConfidentiality(SecurityLevel)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels_DataConfidentiality()
	 * @model default="SL4" unique="false" required="true"
	 * @generated
	 */
	SecurityLevel getDataConfidentiality();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getDataConfidentiality <em>Data Confidentiality</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Data Confidentiality</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #getDataConfidentiality()
	 * @generated
	 */
	void setDataConfidentiality(SecurityLevel value);

	/**
	 * Returns the value of the '<em><b>Restricted Data Flow</b></em>' attribute.
	 * The default value is <code>"SL4"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.SecurityLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Restricted Data Flow</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #setRestrictedDataFlow(SecurityLevel)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels_RestrictedDataFlow()
	 * @model default="SL4" unique="false" required="true"
	 * @generated
	 */
	SecurityLevel getRestrictedDataFlow();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getRestrictedDataFlow <em>Restricted Data Flow</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Restricted Data Flow</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #getRestrictedDataFlow()
	 * @generated
	 */
	void setRestrictedDataFlow(SecurityLevel value);

	/**
	 * Returns the value of the '<em><b>Timely Response</b></em>' attribute.
	 * The default value is <code>"SL4"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.SecurityLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Timely Response</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #setTimelyResponse(SecurityLevel)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels_TimelyResponse()
	 * @model default="SL4" unique="false" required="true"
	 * @generated
	 */
	SecurityLevel getTimelyResponse();

	/**
	 * Returns the value of the ith security level in the vector.
	 * In order: Authentication, useControl, systemIntegrity, dataConfidentiality, restrictedDataFlow, timelyResponse, resourceAvailability
	 * @generated NOT
	 */
	SecurityLevel getSecurityLevel(int i);

	/**
	 * Modify the value of the ith security level in the vector.
	 * In order: Authentication, useControl, systemIntegrity, dataConfidentiality, restrictedDataFlow, timelyResponse, resourceAvailability
	 * @generated NOT
	 */
	void setSecurityLevel(int i, SecurityLevel sl);

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getTimelyResponse <em>Timely Response</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Timely Response</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #getTimelyResponse()
	 * @generated
	 */
	void setTimelyResponse(SecurityLevel value);

	/**
	 * Returns the value of the '<em><b>Resource Availability</b></em>' attribute.
	 * The default value is <code>"SL4"</code>.
	 * The literals are from the enumeration {@link org.xtext.iec62443.baseModel.mIEC.SecurityLevel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Resource Availability</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #setResourceAvailability(SecurityLevel)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getSecurityLevels_ResourceAvailability()
	 * @model default="SL4" unique="false" required="true"
	 * @generated
	 */
	SecurityLevel getResourceAvailability();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.SecurityLevels#getResourceAvailability <em>Resource Availability</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Resource Availability</em>' attribute.
	 * @see org.xtext.iec62443.baseModel.mIEC.SecurityLevel
	 * @see #getResourceAvailability()
	 * @generated
	 */
	void setResourceAvailability(SecurityLevel value);

} // SecurityLevels
