/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ternary Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.TernaryOp#getOp1 <em>Op1</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.TernaryOp#getOp2 <em>Op2</em>}</li>
 *   <li>{@link org.xtext.iec62443.baseModel.mIEC.TernaryOp#getOp3 <em>Op3</em>}</li>
 * </ul>
 *
 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getTernaryOp()
 * @model
 * @generated
 */
public interface TernaryOp extends BooleanExpression, NumberExpression, StringExpression {
	/**
	 * Returns the value of the '<em><b>Op1</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Op1</em>' containment reference.
	 * @see #setOp1(Expression)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getTernaryOp_Op1()
	 * @model containment="true" required="true"
	 * @generated
	 */
	Expression getOp1();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.TernaryOp#getOp1 <em>Op1</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Op1</em>' containment reference.
	 * @see #getOp1()
	 * @generated
	 */
	void setOp1(Expression value);

	/**
	 * Returns the value of the '<em><b>Op2</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Op2</em>' containment reference.
	 * @see #setOp2(Expression)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getTernaryOp_Op2()
	 * @model containment="true" required="true"
	 * @generated
	 */
	Expression getOp2();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.TernaryOp#getOp2 <em>Op2</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Op2</em>' containment reference.
	 * @see #getOp2()
	 * @generated
	 */
	void setOp2(Expression value);

	/**
	 * Returns the value of the '<em><b>Op3</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Op3</em>' containment reference.
	 * @see #setOp3(Expression)
	 * @see org.xtext.iec62443.baseModel.mIEC.MIECPackage#getTernaryOp_Op3()
	 * @model containment="true" required="true"
	 * @generated
	 */
	Expression getOp3();

	/**
	 * Sets the value of the '{@link org.xtext.iec62443.baseModel.mIEC.TernaryOp#getOp3 <em>Op3</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Op3</em>' containment reference.
	 * @see #getOp3()
	 * @generated
	 */
	void setOp3(Expression value);

} // TernaryOp
