/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.iec62443.baseModel.mIEC.FloatExpression;
import org.xtext.iec62443.baseModel.mIEC.MIECPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Float Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public abstract class FloatExpressionImpl extends NumberExpressionImpl implements FloatExpression {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FloatExpressionImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MIECPackage.Literals.FLOAT_EXPRESSION;
	}

} //FloatExpressionImpl
