/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC.impl;

import org.eclipse.emf.ecore.EClass;
import org.xtext.iec62443.baseModel.mIEC.Constraint;
import org.xtext.iec62443.baseModel.mIEC.MIECPackage;
import org.xtext.iec62443.baseModel.mIEC.PresenceConstraint;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Presence Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PresenceConstraintImpl extends ConstraintImpl implements PresenceConstraint {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PresenceConstraintImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MIECPackage.Literals.PRESENCE_CONSTRAINT;
	}

	@Override
	public int getTypeConstraint() {
		return Constraint.PRESENCE;
	}

} //PresenceConstraintImpl
