/**
 * generated by Xtext 2.31.0
 */
package org.xtext.iec62443.baseModel.mIEC.impl;

import org.eclipse.emf.ecore.EClass;
import org.xtext.iec62443.baseModel.mIEC.Application;
import org.xtext.iec62443.baseModel.mIEC.BooleanValue;
import org.xtext.iec62443.baseModel.mIEC.Device;
import org.xtext.iec62443.baseModel.mIEC.FloatValue;
import org.xtext.iec62443.baseModel.mIEC.IntegerValue;
import org.xtext.iec62443.baseModel.mIEC.MIECPackage;
import org.xtext.iec62443.baseModel.mIEC.Property;
import org.xtext.iec62443.baseModel.mIEC.SelfReference;
import org.xtext.iec62443.baseModel.mIEC.StringValue;
import org.xtext.iec62443.baseModel.mIEC.Value;
import org.xtext.iec62443.baseModel.mIEC.ValueOrReference;
import org.xtext.iec62443.baseModel.mIEC.NumberExpression.ComputationErrorException;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Self Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SelfReferenceImpl extends ReferenceImpl implements SelfReference {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelfReferenceImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MIECPackage.Literals.SELF_REFERENCE;
	}

	@Override
	public Value getValue() {
		String pname = this.getReference();
		for(Property p : ((Application)this.eContainer.eContainer()).getProperties()) {
			if (p.getName().equals(pname)) return p.getValue();
		}
		return null;
	}

	@Override
	public Value getValue(Device d) {
		return getValue();
	}

	@Override
	public int getRefType() {
		return ValueOrReference.SELFREF;
	}
	 
		@Override
		public float computeValue(Application a, Device d) throws ComputationErrorException {
			if (a.getProperty(this.reference)!=null) {
				Value val = a.getProperty(this.reference).getValue();
				if (val.getType() == Value.INTEGER) {
					return ((IntegerValue) val).computeValue(a,d);
				}
				if (val.getType() == Value.FLOAT) {
					return ((FloatValue) val).computeValue(a,d);
					
				}
				throw new ComputationErrorException("Error in self reference: mistyped property");
			}
			throw new ComputationErrorException("Error in self reference: no such property");
		}



		@Override
		public boolean getBooleanRes(Application a, Device d) throws ComputationErrorException {
			if (a.getProperty(this.reference)!=null) {
				Value val = a.getProperty(this.reference).getValue();
				if (val.getType() == Value.BOOLEAN) {
					return ((BooleanValue) val).getBooleanRes(a,d);
				}
				throw new ComputationErrorException("Error in device reference: mistyped property");
			}
			throw new ComputationErrorException("Error in device reference: no such property");
		}

		@Override
		public String computeString(Application a, Device d) throws ComputationErrorException {
		if (a.getProperty(this.reference)!=null) {
			Value val = a.getProperty(this.reference).getValue();
			if (val.getType() == Value.BOOLEAN) {
				return ((StringValue) val).computeString(a,d);
			}
			throw new ComputationErrorException("Error in device reference: mistyped property");
		}
		throw new ComputationErrorException("Error in device reference: no such property");
		}
		


		@Override
		public String ExpressiontoString() {
			return "this." + reference;
		}
	

} //SelfReferenceImpl
