/*
 * generated by Xtext 2.32.0
 */
package org.xtext.iec62443.baseModel.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MiecProposalProvider extends AbstractMiecProposalProvider {
}
