/*
 * generated by Xtext 2.32.0
 */
package org.xtext.iec62443.baseModel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.iec62443.baseModel.MiecRuntimeModule;
import org.xtext.iec62443.baseModel.MiecStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MiecIdeSetup extends MiecStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MiecRuntimeModule(), new MiecIdeModule()));
	}
	
}
