/*
 * generated by Xtext 2.32.0
 */
package org.xtext.iec62443.baseModel;

import org.eclipse.emf.ecore.EPackage;
import org.xtext.iec62443.baseModel.mIEC.MIECPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MiecStandaloneSetup extends MiecStandaloneSetupGenerated {

	public static void doSetup() {
		new MiecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	

	@Override
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey(MIECPackage.eNS_URI)) {
			EPackage.Registry.INSTANCE.put(MIECPackage.eNS_URI,
			MIECPackage.eINSTANCE);
		}
		super.register(injector);
		}
}
