/*
 * generated by Xtext 2.32.0
 */
package org.xtext.iec62443.baseModel;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.naming.DefaultDeclarativeQualifiedNameProvider;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.serializer.sequencer.LegacyTransientValueService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */

@SuppressWarnings("all")
public class MiecRuntimeModule extends AbstractMiecRuntimeModule {
  public Class<? extends LegacyTransientValueService> bindITransientValueService2() {
    return MiecTransientValueService.class;
  }
	static class IQualifiedNameProvider2 extends DefaultDeclarativeQualifiedNameProvider {


		@Override
		public QualifiedName getFullyQualifiedName(EObject obj) {
			QualifiedName newName = super.getFullyQualifiedName(obj);
			if (newName == null) {
				return null;
			}
			String name = newName.getLastSegment();
			newName = QualifiedName.create(name);
			return newName;
		}
		
	}
  
	// contributed by org.eclipse.xtext.xtext.generator.exporting.QualifiedNamesFragment2
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return IQualifiedNameProvider2.class;
	}
  
}
